name: Auto Increment Version and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "tag=${latest_tag}" >> "$GITHUB_OUTPUT"
          echo "## Old Tag: $latest_tag" >> "$GITHUB_STEP_SUMMARY"

      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: steps.increment_version.outputs.new_tag != ''
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.get_tag.outputs.tag }}
          prerelease: false
          title: "Release ${{ steps.increment_version.outputs.new_tag }}"

      - name: Summary
        run: |
          echo "## New Tag: ${{ steps.create_release.outputs.automatic_releases_tag }}" >> "$GITHUB_STEP_SUMMARY"
