name: Auto Increment Version and Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "tag=${latest_tag}" >> "$GITHUB_OUTPUT"
          echo "## Old Tag: $latest_tag" >> "$GITHUB_STEP_SUMMARY"

      - name: Increment version
        if : steps.get_tag.outputs.tag != ''
        id: increment_version
        run: |
          current_tag=${{ steps.get_tag.outputs.tag }}
          # Parse the current version number
          major=$(echo $current_tag | cut -d. -f1)
          minor=$(echo $current_tag | cut -d. -f2)
          patch=$(echo $current_tag | cut -d. -f3)

          # Increment the version based on your rules (e.g., incrementing patch version)
          new_patch=$((patch + 1))
          new_tag="$major.$minor.$new_patch"

          echo "new_tag=$new_tag" >> "$GITHUB_OUTPUT"
          echo "## New Tag: $new_tag" >> "$GITHUB_STEP_SUMMARY"

      - name: Set new tag
        if: steps.increment_version.outputs.new_tag != ''
        uses: rickstaa/action-create-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.increment_version.outputs.new_tag }}
          message: ""

      - name: Create Release
        uses: actions/create-release@v1
        if: steps.increment_version.outputs.new_tag != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.increment_version.outputs.new_tag }}
          release_name: Release ${{ steps.increment_version.outputs.new_tag }}
          draft: false
          prerelease: false
