name: Auto Increment Version and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "{tag}={$latest_tag} >> $GITHUB_OUTPUT"

      - name: Increment version
        id: increment_version
        run: |
          current_tag=${{ steps.get_tag.outputs.tag }}
          # Parse the current version number
          major=$(echo $current_tag | cut -d. -f1)
          minor=$(echo $current_tag | cut -d. -f2)
          patch=$(echo $current_tag | cut -d. -f3)

          # Increment the version based on your rules (e.g., incrementing patch version)
          new_patch=$((patch + 1))
          new_tag="$major.$minor.$new_patch"

          echo "{new_tag}={$new_tag} >> $GITHUB_OUTPUT"

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: steps.increment_version.outputs.new_tag != ''
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.increment_version.outputs.new_tag }}
          prerelease: false
          title: "Release ${{ steps.increment_version.outputs.new_tag }}"
